name: PR and Turbo
on: pull_request
jobs:
  lint-check-test:
    permissions:
      contents: 'read'
      actions: 'read'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0 # nx needs the full history

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.1

      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i --frozen-lockfile

      # if run on a PR, origin/main won't exist
      - name: Track main branch
        if: ${{ github.event_name == 'pull_request' }}
        run: git branch --track main origin/main

      - name: Run checks and tests
        run: pnpm turbo run format-check lint build test --filter=\[origin/main\]
