name: Release my-project
on:
  workflow_call:
    inputs:
      releaseName:
        required: true
        type: string
      releaseVersion:
        required: true
        type: string
      releaseBuildNumber:
        required: false
        type: string
jobs:
  mobile-app-android:
    runs-on: ubuntu-latest
    environment: my-project
    if: ${{ contains( inputs.releaseName, 'mobile-app' ) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.3.0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.1

      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup ruby
        uses: ruby/setup-ruby@v1.139.0
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: ./apps/my-project/mobile-app

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Release ios app
        env:
          RELEASE_VERSION: ${{ inputs.releaseVersion }}
          BUILD_NUMBER: ${{ inputs.releaseBuildNumber }}
        run: pnpm run --filter my-project-mobile-app fastlane ci_build_android version:"$RELEASE_VERSION-$BUILD_NUMBER"

  mobile-app-ios:
    runs-on: ubuntu-latest
    environment: my-project
    if: ${{ contains( inputs.releaseName, 'mobile-app' ) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.3.0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.1

      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Setup ruby
        uses: ruby/setup-ruby@v1.139.0
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: ./apps/my-project/mobile-app

      - name: Bootstrap
        run: pnpm run --filter my-project-mobile-app bootstrap 

      - name: Release ios app
        env:
          RELEASE_VERSION: ${{ inputs.releaseVersion }}
          BUILD_NUMBER: ${{ inputs.releaseBuildNumber }}
        run: pnpm run --filter my-project-mobile-app fastlane ci_upload_to_testflight version:"$RELEASE_VERSION-$BUILD_NUMBER"

  backend:
    runs-on: ubuntu-latest
    environment: my-project
    if: ${{ contains( inputs.releaseName, 'backend' ) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.3.0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.1

      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Release backend
        run: pnpm run --filter my-project-backend release 
