name: release-dev

on:
  push:
    branches:
      - main

jobs:
  release-dev:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0 # nx needs the full history

      # set base and head sha's for nx affected commands
      - uses: nrwl/nx-set-shas@v3.0.2

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.27.1

      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Release affected
        run: pnpm nx affected --target=release
