name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3.7.4
        id: release
        with:
          command: manifest

      - name: Get released project
        if: ${{ steps.release.outputs.releases_created }}
        id: get-project-name
        uses: actions/github-script@v6.4.0
        env:
          RELEASE_OUTPUTS: ${{ toJson(steps.release.outputs) }}
        with:
          script: |
            try {
              const releaseOutputs = JSON.parse(process.env['RELEASE_OUTPUTS']);
              const paths_released = JSON.parse(releaseOutputs.paths_released);
              if (!Array.isArray(paths_released) || paths_released.length !== 1)
                throw new Error('expected paths_released to be an array an of length 1');
              let releaseName;
              for (const [key, value] of Object.entries(releaseOutputs)) {
                if (key.endsWith('--name')) {
                  if (!releaseName) {
                    releaseName = value;
                  } else {
                    throw new Error('Multiple keys ending with --name found');
                  }
                }
              }
              if (!releaseName) throw new Error('No release name found');
              // the value should look like e.g.: odensenoeglen-backend: v1.0.0
              const releaseNameArray = releaseName.split(': v');
              if (releaseNameArray.length !== 2 || releaseNameArray[0].length < 1) {
                throw new Error('Unexpected release name format');
              }
              return releaseNameArray[0];
            } catch (error) {
              core.setFailed(`Failed to get project name: ${error}`);
            }

      - name: Check out repository code
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3.3.0

      - uses: pnpm/action-setup@v2.2.4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          version: 7.27.1

      - name: Setup node
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install deps
        if: ${{ steps.release.outputs.releases_created }}
        run: pnpm i --frozen-lockfile

      - run: 'pnpm nx run $PROJECT_NAME:build'
        if: ${{ steps.release.outputs.releases_created }}
        env:
          PROJECT_NAME: ${{ steps.get-project-name.outputs.result }}

      - run: 'pnpm nx run $PROJECT_NAME:release'
        if: ${{ steps.release.outputs.releases_created }}
        env:
          PROJECT_NAME: ${{ steps.get-project-name.outputs.result }}
