name: Release my-project
on:
  workflow_call:
    inputs:
      releaseName:
        required: true
        type: string
      releaseVersion:
        required: true
        type: string
      releaseBuildNumber:
        required: false
        type: string
jobs:
  mobile-app-android:
    runs-on: ubuntu-latest
    environment: my-project
    needs: get-version
    if: ${{ contains( inputs.releaseName, 'mobile-app' ) }}
    steps:
      - name: Check out repository code
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3.3.0

      - uses: pnpm/action-setup@v2.2.4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          version: 7.27.1

      - name: Setup node
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install deps
        if: ${{ steps.release.outputs.releases_created }}
        run: pnpm i --frozen-lockfile

      - name: Bootstrap
        run: pnpm nx bootstrap my-project-mobile-app

      - name: Release ios app
        env:
          RELEASE_VERSION: ${{ needs.get-version.outputs.version }}
          BUILD_NUMBER: ${{ needs.get-version.outputs.buildNumber }}
        run: pnpm nx fastlane my-project-mobile-app -- ci_build_android version:"$RELEASE_VERSION-$BUILD_NUMBER"

  mobile-app-ios:
    runs-on: ubuntu-latest
    environment: my-project
    needs: get-version
    if: ${{ contains( inputs.releaseName, 'mobile-app' ) }}
    steps:
      - name: Check out repository code
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3.3.0

      - uses: pnpm/action-setup@v2.2.4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          version: 7.27.1

      - name: Setup node
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install deps
        if: ${{ steps.release.outputs.releases_created }}
        run: pnpm i --frozen-lockfile

      - name: Bootstrap
        run: pnpm nx bootstrap my-project-mobile-app

      - name: Release ios app
        env:
          RELEASE_VERSION: ${{ needs.get-version.outputs.version }}
          BUILD_NUMBER: ${{ needs.get-version.outputs.buildNumber }}
        run: pnpm nx fastlane my-project-mobile-app -- ci_upload_to_testflight version:"$RELEASE_VERSION-$BUILD_NUMBER"
